name: Build and Publish Python Package

on:
  release:
    types: [created]

env:
  TARGET_PYTHON_VERSION: '3.10'
  TARGET_POETRY_VERSION: '1.8.3'

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
        poetry-version: ["1.6.1", "1.7.1"]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup poetry
        uses: abatilo/actions-poetry@v2.4.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: install dependencies
        run: poetry install --with test --without dev

      - name: run tests
        run: |
          poetry run pytest

      - name: poetry config
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build & publish package
        if: matrix.python-version == env.TARGET_PYTHON_VERSION && matrix.poetry-version == env.TARGET_POETRY_VERSION
        run: poetry publish --build
