name: Build and Publish Python Package

on:
  release:
    types: [created]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.10"]
        poetry-version: ["1.5.1"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python and poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: poetry install --with test --without dev

      - name: Run the tests (sanity check)
        run: |
          poetry run pytest

      - name: Set Poetry Config
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build & publish package
        if: matrix.python-version == '3.10'
        run: poetry publish --build
